---
ConnectionStrings:
  ICloseDbContext: Server=localhost;Database=iclose;Username=postgres;Password=Admin$123
Authentication:
  Authority: http://localhost:8005
  ApiName: icloseAPI
  RequireHttpsMetadata: false
  LegacyAudienceValidation: true
AllowedOrigins:
- http://localhost:4200
- http://localhost:4100
- http://localhost
- http://api.dev.iclose.ca
- https://iclose.ca
EmailConfiguration:
  Host: smtp.gmail.com
  Port: 465
  Username: icloseapp786@gmail.com
  Password: Iclose_app321
  From: icloseapp786@gmail.com
Logging:
  IncludeScopes: false
  Debug:
    LogLevel:
      Default: Warning
  Console:
    LogLevel:
      Default: Warning
HistoryLog:
  Enabled: true
Swagger:
  Enabled: true
StewartConfiguration:
  IdentityBaseUrl: https://test-identity.stewartintltest.com
  BaseUrl: https://www.stewartnextsteps.net
  ClientId: parnes_rothman
  ClientSecret: IUtUTjNXRjZOOSk0K3ItPw==
  GrantType: refresh_token
  RefreshToken: PEU8BqryRqXO1fPpcnHiQ2jMbbxqRkQq0TagNFluXkM
CMSConfiguration:
  BaseUrl: http://api.uat.flinks.iclose.ca
  TemplateId: 203d7601-75b7-4a5e-9568-4dd1209cfee8
FCTConfiguration:
  ProcessPath: C:\inetpub\wwwroot\Debug\ConsoleApplicationFCT.exe
  BaseUrl: https://fctexintgsg10.prefirstcdn.com
  PartnerToken: 9218E77C-154D-4C23-BEF8-8E74D5CA3FA6
  AuthenticatedFctUser: srothman
  PartnerUserName: bdyendurhampreprod
  FirstName: Active
  LastName: LastName
  BusinessRole: LAWYER
  FctUserName: ''
FCTLLCConfiguration:
  BaseUrl: https://fctllcintgsg01.firstcdn.com
Serilog:
  MinimumLevel:
    Default: Error
    Override:
      System: Information
      Microsoft: Information
  WriteTo:
  - Name: File
    Args:
      path: Logs\iCloseLogs.json
      formatter: Serilog.Formatting.Json.JsonFormatter, Serilog
      rollingInterval: Day
  - Name: Seq
    Args:
      serverUrl: http://localhost:5341
      apiKey: none
      restrictedToMinimumLevel: Verbose
  Enrich:
  - FromLogContext
  - WithMachineName
  - WithProcessId
  - WithThreadId
  - WithExceptionDetails
  Properties:
    Application: iClose
DomainConfigurations:
  Domain: http://dev.iclose.ca/iclose
  ResetPasswordPath: "/#/pages/resetpassword/"
ApplicationSettings:
  Identity:
    Authority: http://localhost:8005
ClientServiceConfigurations:
  BaseUrl: http://localhost:8007
VerifiedMe:
  BaseUrl: https://testnet-realestatelawyers6640-dac-adapter.hosting.vme.dev
  LicenseNotificationUrl: https://api.dev.iclose.ca/local-iclose-api/v1/verifiedme/LicenseNotification
  RedirectUrl: https://dev.iclose.ca/clientportal/#/identity
  XAPIKey: daewk5wd.awpndsxy6ukdf6oiqr74uc3o419agdhish
ChicagoTitle:
  BaseUrl: https://ctiwsstage.ctic.ca
  SystemToken: FF4D6B54-C44E-4BCA-9795-9B1E190E1F1E
spring:
  application:
    name: my-values
  cloud:
    config:
      uri: http://localhost:8888
      validateCertificates: false
      label: main
